export interface SweepVariable {
  id: string;
  name: string;
  start: number;
  stop: number;
  step: number;
  units: string;
}

export interface ScriptConfig {
  targetPlatform: 'windows' | 'linux';
  setupName: string;
  parametricSetupName: string;
  variables: SweepVariable[];
  exportPath: string;
  filenamePrefix: string;
  includeVarInName: boolean;
}

export const generateHfssScript = (config: ScriptConfig): string => {
  const {
    targetPlatform,
    setupName,
    parametricSetupName,
    variables,
    exportPath,
    filenamePrefix,
    includeVarInName,
  } = config;

  // Format variables for Python list
  const pyVariables = variables.map(v => 
    `    {"name": "${v.name}", "start": ${v.start}, "stop": ${v.stop}, "step": ${v.step}, "units": "${v.units}"}`
  ).join(',\n');

  const scriptContent = `# HFSS Automation Script
# Generated by HFSS AutoScript Gen
# Target Platform: ${targetPlatform === 'linux' ? 'Linux (CentOS/RHEL)' : 'Windows'}
# -----------------------------------------------------------------------
import ScriptEnv
import os

# --- Configuration Section ---
parametric_setup_name = "${parametricSetupName}"
solution_setup_name = "${setupName}"
# Note: On Linux, ensure the path exists and is writable.
export_folder = r"${exportPath}"
filename_prefix = "${filenamePrefix}"
include_var_in_filename = ${includeVarInName ? 'True' : 'False'}

# List of variables to sweep
# Format: {name, start, stop, step, units}
sweep_variables = [
${pyVariables}
]

# -----------------------------------------------------------------------
# Initialize HFSS
ScriptEnv.Initialize("Ansoft.ElectronicsDesktop")
oDesktop = ScriptEnv.GetDesktop()

# Attempt to restore window (Safe for Linux/Batch mode)
try:
    oDesktop.RestoreWindow()
except:
    # This often fails in Linux batch mode (-ng), which is fine.
    pass

oProject = oDesktop.GetActiveProject()
if oProject is None:
    print("Error: No active project found. Please open a project first.")
    # In a real script you might want to exit or raise error
else:
    oDesign = oProject.GetActiveDesign()
    if oDesign is None:
        print("Error: No active design found.")
    else:
        oModule = oDesign.GetModule("Solutions")

def float_range(start, stop, step):
    """Generator for float range with epsilon safety."""
    # Handle case where step is 0 or invalid to avoid infinite loop
    if step <= 0:
        yield start
        return

    current = start
    # Using a small epsilon to handle floating point precision issues at the boundary
    epsilon = step / 1000.0
    while current <= stop + epsilon:
        yield current
        current += step

def get_combinations(vars_list, current_combo=[]):
    """
    Recursively generate all combinations of variable values.
    Returns a list of tuples: [(var_name, val_string), ...]
    """
    if not vars_list:
        yield current_combo
        return

    var_data = vars_list[0]
    name = var_data["name"]
    start = var_data["start"]
    stop = var_data["stop"]
    step = var_data["step"]
    units = var_data["units"]

    for val in float_range(start, stop, step):
        # Format value
        # Adjust precision as needed, default 4 decimal places
        val_str = "{:.4f}".format(val)
        if units:
            val_str += units
            
        # Recurse for the next variable
        new_combo = current_combo + [(name, val_str)]
        for res in get_combinations(vars_list[1:], new_combo):
            yield res

def main():
    if oProject is None or oDesign is None:
        return

    # 1. Run the Parametric Sweep
    print("Starting Analysis: " + parametric_setup_name)
    # Note: This runs the setup defined in HFSS. Ensure the setup in HFSS 
    # matches the variables defined in this script for the loop below to work correctly.
    try:
        oDesign.Analyze(parametric_setup_name)
        print("Analysis Completed Successfully.")
    except Exception as e:
        print("Analysis failed or stopped. Error: " + str(e))
        # We continue to try exporting just in case results already exist

    # 2. Export SNP Files
    if not os.path.exists(export_folder):
        print("Export folder does not exist. Creating: " + export_folder)
        try:
            os.makedirs(export_folder)
        except Exception as e:
            print("Failed to create directory. Check permissions. Error: " + str(e))
            return

    print("Starting Export...")
    
    count = 0
    # Iterate through all combinations generated by our python logic
    for combo in get_combinations(sweep_variables):
        # combo is like [('L', '10mm'), ('W', '2mm')]
        
        # Construct the Variation String used by HFSS
        # Syntax example: "L='10mm' W='2mm'"
        variation_parts = ["{}='{}'".format(item[0], item[1]) for item in combo]
        variation_string = " ".join(variation_parts)
        
        # Construct Filename
        # If enabled, append all variable values: Prefix_L_10mm_W_2mm.s2p
        if include_var_in_filename:
            var_suffix_parts = ["{}_{}".format(item[0], item[1]) for item in combo]
            var_suffix = "_".join(var_suffix_parts)
            fname = "{}_{}.s2p".format(filename_prefix, var_suffix)
        else:
            var_suffix_parts = ["{}".format(item[1]) for item in combo]
            var_suffix = "_".join(var_suffix_parts)
            fname = "{}_{}.s2p".format(filename_prefix, var_suffix)
            
        full_path = os.path.join(export_folder, fname)
        
        try:
            print("Exporting: " + variation_string)
            oModule.ExportNetworkData(
                solution_setup_name, 
                full_path, 
                3, # Format: 3 for Touchstone (.sNp)
                False, # Complex magnitude?
                variation_string
            )
            count += 1
        except Exception as e:
            print("Failed to export combination: " + variation_string)
            # print("Error: " + str(e)) 

    print("All tasks finished. Total exported: " + str(count))

if __name__ == "__main__":
    main()
`;

  return scriptContent;
};
